# Generated by Django 3.0.3 on 2020-05-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestap',
        ),
        migrations.RemoveField(
            model_name='post',
            name='wonar',
        ),
    ]
