# Generated by Django 3.0.3 on 2020-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200504_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripction',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
