# Generated by Django 3.0.3 on 2020-05-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200504_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestap',
        ),
        migrations.RemoveField(
            model_name='post',
            name='wonar',
        ),
    ]
